### ISSUE TITLE
jsx preserve mode doesn't work

### ISSUE THREAD

**Issue by easylogic** [cometkim/nanobundle#61]
We are building with the latest version.

The jsx syntax in the tsx file is expressed as it is without being built.

Is there no way?

```tsx
// index.mjs

  const buttonContent = <span>{children || ""}</span>;
```

The expected expression is:

```js
const buttonContent = React.createElement("span", null, children || "");
```

Both cjs and mjs are the same.

jsx syntax doesn't compile.

---- 

```json
// tsconfig 

{
    compilerOptions: {
        jsx: "react"  // not working 
        jsx: "react-jsx" // compile with jsx function 
    }

}

```

**Comment by cometkim** [comment]
this has fixed in rc.12

**Comment by easylogic** [comment]
I will try it  with rc.12.

**Comment by easylogic** [comment]
rc.12 is not exsits in npmjs. 

how to install this version?

**Comment by cometkim** [comment]
rc 12 is exist in `@rc` channel
![image](https://user-images.githubusercontent.com/9696352/206859897-0880b67f-b685-4820-ba62-6cd8d25cd3a7.png)

**Comment by easylogic** [comment]
@cometkim 

i installed rc.12 

but It is still not working .

**Comment by cometkim** [comment]
Hmm let me take a look.

**Comment by cometkim** [comment]
I guess it is because of tree-shaking. Can you try again with actually exporting to your module tree?

**Comment by cometkim** [comment]
![image](https://user-images.githubusercontent.com/9696352/206860629-87ebceae-7b2a-4d6f-a5cd-e219d607c5fa.png)
I see your Button component is compiling properly

**Comment by easylogic** [comment]
it is old version compile.

**Comment by easylogic** [comment]
I also found  other error. 
If you define "moduleResolution": "NodeNext", in tsconfig, the following error occurs.


```ts

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
@react-elf/shared:build:     at result2tsconfig (file:///Users/user/github/test/react-elf/node_modules/tsconfck/dist/index.js:675:83)
@react-elf/shared:build:     at parseFile2 (file:///Users/user/github/test/react-elf/node_modules/tsconfck/dist/index.js:622:15)
@react-elf/shared:build:     at parseNative (file:///Users/user/github/test/react-elf/node_modules/tsconfck/dist/index.js:588:20)
@react-elf/shared:build:     at async it (file:///Users/user/github/test/react-elf/node_modules/nanobundle/bin.min.mjs:151:104)

```

**Comment by cometkim** [comment]
Yeah, it's caused by upstream :sweat_smile: 

I've already submitted PR to fix that https://github.com/dominikg/tsconfck/pull/73

**Comment by cometkim** [comment]
> it is old version compile.

So does it means you want jsxFactory from React 18?

**Comment by easylogic** [comment]
I want it to be built in the form of React.createElement function.

Existing esbuild worked like that.

This worked similarly to vite, so I thought I could use it as it is.

**Comment by cometkim** [comment]
Ah my fault, compiles are belong to `dist` I see

**Comment by cometkim** [comment]
I will publish it as rc.13 soon

**Comment by cometkim** [comment]
rc.13 is just published

**Comment by easylogic** [comment]
good. 

i will test it .

**Comment by easylogic** [comment]
Oh it works fine.

The compilation result is good.

```jsx
  const buttonContent = /* @__PURE__ */ React.createElement("span", null, children || "");
```
